version: '3.8'

services: 
  docker-mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main
      - MYSQL_USER=user
      - MYSQL_PASSWORD=P@ssword
      - MYSQL_HOST=localhost
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 4s
      timeout: 20s
      retries: 20
    networks:
      - backend

  flyway:
    image: boxfuse/flyway
    command: -url=jdbc:mysql://docker-mysql:3306/main -schemas=main -user=user -password=P@ssword migrate
    volumes:
     - "./local-setup/sql:/flyway/sql"
    depends_on:
      docker-mysql:
        condition: service_healthy
    networks:
      - backend
  
  spring-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_URL=jdbc:mysql://docker-mysql:3306/main?useSSL=false
      - MYSQL_USER=user
      - MYSQL_PASSWORD=P@ssword
    depends_on:
      - docker-mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge