version: '3.8'  # Specify the version of Docker Compose

services:
  mysql:
    image: mysql:8.0  # MySQL image version 8.0
    container_name: mysql_container  # Optional: Name for the container
    restart: always  # Restart policy
    ports:
      - "3306:3306"  # Map port 3306 on the host to port 3306 on the container
    environment:
      MYSQL_ROOT_PASSWORD: root  # Root password for MySQL
      MYSQL_DATABASE: main  # Optional: Database to create on startup
      MYSQL_USER: user  # Optional: Create a new user
      MYSQL_PASSWORD: P@ssword  # Optional: Password for the new user
    volumes:
      - mysql_data:/var/lib/mysql  # Mount a volume to persist data

volumes:
  mysql_data:
    driver: local  # Use local volume driver

# Optionally, you can add more services or configurations as needed.
